# Generated by Django 5.2.1 on 2025-05-26 08:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0441d32f-4307-43ce-8061-75866864f705'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('404be9eb-1eb8-43cf-948a-db6fca17a657'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
